all:
	make -f Makefile.ACO all
	make -f Makefile.CHC all
	make -f Makefile.newGA all
	make -f Makefile.SA all
	make -f Makefile.SS all
	make -f Makefile.hybrids all
	make -f Makefile.ES all
	make -f Makefile.PSO all
clean:
	make -f Makefile.ACO clean
	make -f Makefile.CHC clean
	make -f Makefile.newGA clean
	make -f Makefile.SA clean 
	make -f Makefile.SS clean
	make -f Makefile.hybrids clean
	make -f Makefile.ES clean
	make -f Makefile.PSO clean
